############################################################
# Purpose: Dockerfile to build Ubuntu VM python2
# Name: u1404py2
# Date: 2017-03-18
############################################################

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER "Tom Cai" <thomas_cai@yahoo.com>

# Update the repository sources list
RUN apt-get update
RUN apt-get upgrade -y

# Install basic os tools
RUN apt-get install -y net-tools curl vim man tree rsync screen less

# Install ssh
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
ADD ./.ssh /root/.ssh

# Set locale
RUN export LC_C=C

# Install nginx
RUN apt-get install -y nginx

# Install python2.7 related packages
RUN apt-get install -y build-essential python-dev libsqlite3-dev libreadline6-dev libgdbm-dev zlib1g-dev libbz2-dev sqlite3 zip
RUN apt-get install -y python-pip
RUN pip install flask

RUN pip install virtualenv
RUN pip install virtualenvwrapper
RUN mkdir -p ~/venv ~/proj
RUN printf 'export WORKON_HOME=$HOME/venv\nexport PROJECT_HOME=$HOME/proj\nsource /usr/local/bin/virtualenvwrapper.sh' > ~/.bashrc

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]

##################### INSTALLATION END #####################
#  docker build -t u1404py2:01 -f Dockerfile-u1404-python2 .
#  docker run -d --name py2 --hostname py2 -v /Users/tahoe/data:/data -p 8022:22 u1404py2:01
#  ssh localdocker2
#  docker port u1404sshd 22
#  ssh -i .ssh/id_rsa root@localhost -p 8022
#  ssh localdocker
#  docker stop u1404sshd && docker rm -f u1404sshd

