############################################################
# Purpose: Dockerfile to build Ubuntu VM python3 with sshd
# Name: u1404sshd
# Date: 2017-03-15
############################################################

# Set the base image to Ubuntu
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER "Tom Cai" <thomas_cai@yahoo.com>

# Update the repository sources list
RUN apt-get update
RUN apt-get upgrade -y

# Install basic os tools
RUN apt-get install -y net-tools curl vim man tree

# Install ssh
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
ADD ./.ssh /root/.ssh

# Install python2.7 tools
RUN apt-get install -y python-pip
RUN mkdir -p ~/venv ~/proj
RUN pip install virtualenv
RUN pip install virtualenvwrapper
RUN printf 'export WORKON_HOME=$HOME/venv\nexport PROJECT_HOME=$HOME/proj\nsource /usr/local/bin/virtualenvwrapper.sh' > ~/.bashrc

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]

##################### INSTALLATION END #####################
#  docker build -t u1404sshd:01 -f Dockerfile-u1404-sshd .
#  docker run -d -p 8022:22 --name u1404sshd --hostname u1404sshd u1404sshd:01
#  docker port u1404sshd 22
#  ssh -i .ssh/id_rsa root@localhost -p 8022
#  ssh localdocker
#  docker stop u1404sshd && docker rm -f u1404sshd

