############################################################
# Purpose: Dockerfile to build Ubuntu VM with python3
# Name: u1604py3
# Date: 2017-03-05
############################################################

# Set the base image to Ubuntu
FROM u1604sshd:01

# File Author / Maintainer
MAINTAINER "Tom Cai" <thomas_cai@yahoo.com>

# Install python3
RUN apt-get install -y build-essential libssl-dev libffi-dev python-dev
RUN apt-get install -y python3-setuptools
RUN apt-get install -y python3-pip python3-venv ipython3

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

##################### INSTALLATION END #####################

##################### TEST STEPS #####################
#  docker build -t u1604py3:01 -f Dockerfile-u1604sshd-python3 .
#  docker run -d --hostname py3 --name py3 -p 8023:22 -v /User/tahoe:/host u1604py3:01
##################### TEST END #####################
