version: "3"

services:
  py2:
    build:
      context: .
      dockerfile: Dockerfile-u1404sshd-python2
    image: tomkite/u1404py2:01
    container_name: py2
    hostname: py2
    privileged: true
    ports:
      - "8022:22"
      - "8082:80"
    volumes:
      - /Users/tom/data/:/data

  py3:
    build:
      context: .
      dockerfile: Dockerfile-u1604sshd-python3
    image: tomkite/u1604py3:01
    container_name: py3
    hostname: py3
    privileged: true
    ports:
      - "8023:22"
      - "8083:80"
    volumes:
      - /Users/tom/data/:/data
