############################################################
# Purpose: Dockerfile to build Ubuntu VM python3 with sshd
# Name: u1604sshd
# Date: 2017-03-15
############################################################

# Set the base image to Ubuntu
FROM ubuntu:16.04

# File Author / Maintainer
MAINTAINER "Tom Cai" <thomas_cai@yahoo.com>

# Update the repository sources list
RUN apt-get update
RUN apt-get upgrade -y

# Install basic os tools
RUN apt-get install -y net-tools curl vim man tree

# Install ssh
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd
ADD ./.ssh /root/.ssh

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]

##################### INSTALLATION END #####################
#  docker build -t u1604sshd:01 -f Dockerfile-u1604-sshd .
#  docker run -d -p 8022:22 --name u1604sshd --hostname u1604sshd u1604sshd:01
#  docker port u1604sshd 22
#  ssh -i .ssh/id_rsa root@localhost -p 8022
#  ssh localdocker
#  docker stop u1604sshd && docker rm -f u1604sshd

