############################################################
# Purpose: Dockerfile to build Ubuntu VM python3 with sshd
# Name: u1404sshd
# Date: 2017-03-15
############################################################

# Set the base image to Ubuntu
FROM u1404sshd:01

# File Author / Maintainer
MAINTAINER "Tom Cai" <thomas_cai@yahoo.com>

# Update the repository sources list
RUN apt-get update
RUN apt-get upgrade -y

# Install ssh
RUN apt-get install -y nginx

EXPOSE 22
CMD    ["/usr/sbin/sshd", "-D"]

##################### INSTALLATION END #####################
#  docker build -t u1404sshd:02 -f Dockerfile-u1404-sshd-nginx .
#  docker run -d -p 8022:22 -p 8080:80 --name u1404nginx --hostname u1404nginx u1404sshd:02
#  docker port u1404nginx 22
#  curl localhost:8080
#  ssh -i .ssh/id_rsa root@localhost -p 8022
#  ssh localdocker2
#  docker stop u1404nginx && docker rm -f u1404nginx

